### PR TITLE
Allows searches within the portage tree structure

### PR DESCRIPTION
**Pull request by inode64**
I have had to recreate a branch, my strength is not git and I don't use vscode much, I use Jetbarins

### CODE REVIEW

**Comment by Tatsh** [comment]
Just make sure to not create merge commits when pulling. I imagine JetBrains app has a way to do this but you can also set it as default.

https://stackoverflow.com/a/50507965

If you remove --global and run it in this repository, it will only apply to this repo and not anywhere else.

**Comment by inode64** [comment]
OK thanks. I'll use them next time

**Comment by Tatsh** [comment]
What does this change do compared to before?

**Comment by inode64** [comment]
nothing has changed, in the end as I was desperate and couldn't delete the commits I created another branch with the same changes

**Comment by Tatsh** [comment]
I mean what's new to livecheck in this PR?

**Comment by inode64** [comment]
I'm sorry, I didn't explain myself well.
Allows searching in paths or directories other than /usr/portage
For example, you can search for just one directory. 
/usr/portage/dev-lang/ or /usr/portage/app-admin/cockpit
If you want to perform a search you can narrow down

**Comment by Tatsh** [comment]
Okay just to be clear: if I am inside `/var/db/repos/my-overlay/dev-lang/blah/files` it figures out the root `/var/db/repos/my-overlay` and then does the search?

**Comment by inode64** [comment]
Yes, the system now detects the main path of the repository and only searches the assigned directory

**Comment by Tatsh** [comment]
Cool. Thanks.

**Pull request merged**
